# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Davs125/NickUI
build-by-default: true
branches:
  - main
projects:
  NickUI:
    path: ""
    icon: "https://i.ibb.co/DzBckd1/image.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
