# Poggit-CI Manifest for NickUI
build-by-default: true

branches:
  - main

projects:
  - name: "NickUI"
    main: "src/SoyDavs/NickUI/Main.php"
    dependencies:
      - "jojoe77777/FormAPI"
    loader: "phar"
    files:
      - "plugin.yml"
      - "composer.json"
      - "src/"
      - "vendor/"
      - "resources/"
      - "config.yml"
    phar:
      stub: "vendor/autoload.php"
      output: "NickUI.phar"
